# Generated by Django 5.2.14 on 2026-06-02 10:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Currency',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(db_column='Code', max_length=3, unique=True)),
                ('name', models.CharField(db_column='FullName', max_length=100, unique=True)),
                ('sign', models.CharField(db_column='Sign', max_length=3, unique=True)),
            ],
            options={
                'db_table': 'Сurrencies',
            },
        ),
        migrations.CreateModel(
            name='ExchangeRate',
            fields=[
                ('id', models.BigAutoField(db_column='ID', primary_key=True, serialize=False)),
                ('rate', models.DecimalField(db_column='Rate', decimal_places=6, max_digits=10)),
                ('base_currency', models.ForeignKey(db_column='BaseCurrencyId', on_delete=django.db.models.deletion.CASCADE, related_name='base_currencies', to='currency_exchange.currency')),
                ('target_currency', models.ForeignKey(db_column='TargetCurrencyId', on_delete=django.db.models.deletion.CASCADE, related_name='target_currencies', to='currency_exchange.currency')),
            ],
            options={
                'db_table': 'ExchangeRates',
                'constraints': [models.UniqueConstraint(fields=('base_currency_id', 'target_currency_id'), name='target_currency_id_base_currency')],
            },
        ),
        migrations.RunSQL(
            sql="""
        INSERT INTO Сurrencies (Code, FullName, Sign)
        VALUES ("USD", "US Dollar", "$"),
               ("EUR", "Euro", "€"),
               ("Australian dollar", "AUD", "A$");
        """,
            reverse_sql="""
        DELETE FROM Currencies where sign in ($, €, A$);
        """
        )
    ]
